begin;
insert into auth.users(id) values('50000000-0000-0000-0000-000000000001'),('60000000-0000-0000-0000-000000000002') on conflict do nothing;
set local role authenticated;
select set_config('request.jwt.claim.sub','50000000-0000-0000-0000-000000000001',true);
select public.genesis_profile_ensure('Selection test');
select public.genesis_wallet_initialize(0,0);
reset role;
update public.genesis_wallets set gp=240,essence=5000 where user_id='50000000-0000-0000-0000-000000000001';
set local role authenticated;
do $$declare r jsonb;id uuid;other uuid;k text:=gen_random_uuid()::text;before_wallet jsonb;decision jsonb;begin
 r:=public.genesis_v2_summon(10,false,k);
 assert jsonb_array_length(r->'results')=10;
 assert (select count(*) from public.genesis_characters where selection_state='pending' and archived)=10,'new results must wait outside Collection';
 assert (select count(*) from public.genesis_characters where not archived)=0;
 id:=(r->'results'->0->>'registry_id')::uuid;
 other:=(r->'results'->1->>'registry_id')::uuid;
 begin perform public.genesis_character_train(id,1,gen_random_uuid()::text);raise exception 'pending training allowed';exception when raise_exception then if sqlerrm<>'CHARACTER_NOT_FOUND' then raise;end if;end;
 before_wallet:=public.genesis_v2_status()->'wallet';
 decision:=public.genesis_character_decide(id,true);
 assert decision=public.genesis_character_decide(id,true),'Keep retry';
 assert (select count(*) from public.genesis_characters where not archived)=1;
 decision:=public.genesis_character_decide(other,false);
 assert decision=public.genesis_character_decide(other,false),'Discard retry';
 assert (select selection_state='discarded' and archived from public.genesis_characters where registry_id=other);
 assert before_wallet=public.genesis_v2_status()->'wallet','selection must not change economy or pity';
 begin perform public.genesis_character_decide(other,true);raise exception 'discard reversed';exception when raise_exception then if sqlerrm<>'CHARACTER_ALREADY_DECIDED' then raise;end if;end;
 begin perform public.genesis_character_decide(id,false);raise exception 'kept choice reversed';exception when raise_exception then if sqlerrm<>'CHARACTER_ALREADY_DECIDED' then raise;end if;end;
 assert r=public.genesis_v2_summon(10,false,k),'summon retry must not create new pending results';
 assert (select count(*) from public.genesis_characters where selection_state='pending')=8;
 perform public.genesis_character_set_name(id,'Kept Hero');
 assert (select custom_name from public.genesis_characters where registry_id=id)='Kept Hero';
 perform public.genesis_character_train(id,1,gen_random_uuid()::text);
 perform set_config('request.jwt.claim.sub','60000000-0000-0000-0000-000000000002',true);
 assert (select count(*) from public.genesis_characters)=0,'other account cannot read results';
 begin perform public.genesis_character_decide(id,true);raise exception 'cross account allowed';exception when raise_exception then if sqlerrm<>'CHARACTER_NOT_FOUND' then raise;end if;end;
 perform set_config('request.jwt.claim.sub','50000000-0000-0000-0000-000000000001',true);
 begin update public.genesis_characters set selection_state='kept',archived=false where registry_id=other;raise exception 'direct update allowed';exception when insufficient_privilege then null;end;
end;$$;
rollback;
