package com.genesis.gacha;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import android.text.InputType;
import org.json.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

public final class MainActivity extends Activity {
 private final Api api=Api.INSTANCE;
 private final ExecutorService worker=Executors.newSingleThreadExecutor();
 private final ExecutorService images=Executors.newFixedThreadPool(2);
 private final android.util.LruCache<String,Bitmap> cache=new android.util.LruCache<String,Bitmap>(16*1024*1024){protected int sizeOf(String k,Bitmap b){return b.getByteCount();}};
 private CharacterEngine engine;
 private GenesisAudio audio;
 private SanctumRitualView sanctum;
 private GenesisPresentation presentation;
 private JSONObject catalog=new JSONObject(),profile=new JSONObject(),secure=new JSONObject(),meta=new JSONObject(),economy=new JSONObject();
 private JSONArray pending=new JSONArray(),characters=new JSONArray(),history=new JSONArray(),media=new JSONArray();
 private LinearLayout root,body,nav;private TextView status;
 private String page="Home",selected="",search="",filter="All",uploadId="",uploadPrompt="";
 private int pageSize=30;private boolean busy=false,ready=false;private android.content.SharedPreferences prefs;
 private final int bg=Color.rgb(16,11,7),panel=Color.rgb(37,24,15),gold=Color.rgb(214,173,98),muted=Color.rgb(189,169,140),white=Color.rgb(245,234,216);
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("presentation",MODE_PRIVATE);audio=new GenesisAudio(this,prefs);presentation=new GenesisPresentation(this,prefs,audio,this::asset);api.attach(this);if(b!=null){page=b.getString("page","Home");selected=b.getString("selected","");uploadId=b.getString("uploadId","");uploadPrompt=b.getString("uploadPrompt","");}shell();task(()->{engine=new CharacterEngine(assetText("engine.js"));catalog=new JSONObject(assetText("catalog.json"));if(api.signedIn())refresh();return null;},x->{if(api.signedIn()&&ready)render();else login();});}
 @Override public void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putString("page",page);b.putString("selected",selected);b.putString("uploadId",uploadId);b.putString("uploadPrompt",uploadPrompt);}
 @Override public void onResume(){super.onResume();if(sanctum!=null)sanctum.setRunning(true);if(audio!=null)audio.resume();if(presentation!=null)presentation.resume();}
 @Override public void onPause(){if(sanctum!=null)sanctum.setRunning(false);if(presentation!=null)presentation.pause();if(audio!=null)audio.pause();super.onPause();}
 @Override public void onWindowFocusChanged(boolean focus){super.onWindowFocusChanged(focus);if(sanctum!=null)sanctum.setRunning(focus);}
 @Override public void onDestroy(){if(sanctum!=null)sanctum.setRunning(false);if(presentation!=null)presentation.close();if(audio!=null)audio.close();worker.shutdown();images.shutdownNow();cache.evictAll();super.onDestroy();}
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 private JSONObject obj(JSONObject p,String k){JSONObject o=p.optJSONObject(k);return o==null?new JSONObject():o;}
 private JSONArray arr(JSONObject p,String k){JSONArray a=p.optJSONArray(k);return a==null?new JSONArray():a;}
 private JSONObject json(Object... pairs){JSONObject o=new JSONObject();try{for(int i=0;i<pairs.length;i+=2)o.put((String)pairs[i],pairs[i+1]);}catch(JSONException e){throw new IllegalArgumentException(e);}return o;}
 private String assetText(String name)throws Exception {try(InputStream in=getAssets().open(name)){return new String(bytes(in,2000000),java.nio.charset.StandardCharsets.UTF_8);}}
 private static byte[] bytes(InputStream in,int max)throws Exception {ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){if(out.size()+n>max)throw new IOException("File is too large");out.write(b,0,n);}return out.toByteArray();}
 private void shell(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);root.setPadding(dp(16),dp(12),dp(16),dp(8));root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(dp(16),i.getSystemWindowInsetTop()+dp(10),dp(16),i.getSystemWindowInsetBottom()+dp(6));return i;});setContentView(root);TextView brand=text(root,"G E N E S I S",25,gold);brand.setTypeface(Typeface.SERIF);status=text(root,"Connecting…",12,muted);status.setAccessibilityLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);ScrollView sc=new ScrollView(this);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);sc.addView(body);nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);root.addView(nav);}
 private TextView text(LinearLayout p,String s,int size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setPadding(0,dp(5),0,dp(5));p.addView(v);return v;}
 private void note(String s){text(body,s,14,muted);}
 private void heading(String s){TextView v=text(body,s,27,gold);v.setTypeface(Typeface.SERIF);}
 private LinearLayout card(LinearLayout p){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(12),dp(14),dp(12));GradientDrawable d=new GradientDrawable();d.setColor(panel);d.setCornerRadius(dp(12));d.setStroke(dp(1),Color.rgb(83,62,35));c.setBackground(d);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(6),0,dp(8));p.addView(c,lp);return c;}
 private Button button(LinearLayout p,String label,Runnable click){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextSize(13);b.setTextColor(bg);b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(gold));p.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));b.setOnClickListener(v->{if(!busy)click.run();});return b;}
 private EditText input(LinearLayout p,String hint,int type){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(muted);e.setTextColor(white);e.setInputType(type);e.setSingleLine(true);p.addView(e,new LinearLayout.LayoutParams(-1,dp(56)));return e;}
 private void toggle(String label,String key,boolean defaultValue){Switch s=new Switch(this);s.setText(label);s.setTextColor(white);s.setMinHeight(dp(52));s.setChecked(prefs.getBoolean(key,defaultValue));body.addView(s);s.setOnCheckedChangeListener((v,on)->{prefs.edit().putBoolean(key,on).apply();audio.settingsChanged();});}
 private void alert(String s){if(!isFinishing())new AlertDialog.Builder(this).setMessage(s).setPositiveButton("OK",null).show();}
 private String slug(String s){return s.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-").replaceAll("^-|-$","");}
 private void asset(LinearLayout p,String path,int height){if(path.startsWith("media/rarities/v2/")){String key=path.substring(path.lastIndexOf('/')+1).replace(".png","");String[] keys={"common","rare","super-rare","epic","mythic"};int tier=0;for(int i=0;i<keys.length;i++)if(keys[i].equals(key))tier=i;String[] names={"Common","Rare","Super Rare","Epic","Mythic"};int[] colors={0xffb8c3cc,0xff66b9ee,0xff918aff,0xffc066f0,0xffef91c6};TextView badge=text(p,names[tier]+"  "+(tier+3)+"★",22,colors[tier]);badge.setGravity(Gravity.CENTER);badge.setMinHeight(dp(height));GradientDrawable frame=new GradientDrawable();frame.setColor(0xff15111d);frame.setCornerRadius(dp(12));frame.setStroke(dp(2),colors[tier]);badge.setBackground(frame);return;}ImageView v=new ImageView(this);v.setScaleType(ImageView.ScaleType.FIT_CENTER);v.setContentDescription(path.substring(path.lastIndexOf('/')+1).replace(".png","").replace('-',' '));p.addView(v,new LinearLayout.LayoutParams(-1,dp(height)));Bitmap known=cache.get(path);if(known!=null){v.setImageBitmap(known);return;}images.execute(()->{try{BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;try(InputStream in=getAssets().open(path)){BitmapFactory.decodeStream(in,null,o);}o.inSampleSize=1;while(o.outWidth/o.inSampleSize>800||o.outHeight/o.inSampleSize>800)o.inSampleSize*=2;o.inJustDecodeBounds=false;Bitmap b;try(InputStream in=getAssets().open(path)){b=BitmapFactory.decodeStream(in,null,o);}if(b!=null){cache.put(path,b);runOnUiThread(()->{if(!isDestroyed())v.setImageBitmap(b);});}}catch(Exception ignored){}});}
 interface Work{Object run()throws Exception;}interface Done{void run(Object value)throws Exception;}
 private void task(Work work,Done done){if(busy)return;busy=true;status.setText("Connecting to Genesis…");root.setAlpha(.75f);worker.execute(()->{try{Object x=work.run();runOnUiThread(()->{if(isDestroyed())return;busy=false;root.setAlpha(1);try{done.run(x);}catch(Exception e){alert("Could not display the response. Refresh to reload.");}});}catch(Exception e){runOnUiThread(()->{if(isDestroyed())return;busy=false;root.setAlpha(1);if(!api.signedIn())login();else if(!ready){body.removeAllViews();heading("Connection needs attention");note("This edition requires the Genesis V17.1 selection migration. Check UPDATE-V17.md.");button(body,"Try again",()->task(()->{refresh();return null;},x->render()));button(body,"Sign out",this::logout);}status.setText("Connection interrupted");alert(e.getMessage()==null?"Request failed. Please retry.":e.getMessage());});}});}
 private JSONObject rpc(String name,JSONObject args)throws Exception{return api.rpc(name,args);}
 private void refresh()throws Exception{
  JSONObject p=rpc("genesis_profile_ensure",new JSONObject());JSONObject s=rpc("genesis_secure_snapshot",new JSONObject());
  if(!s.optBoolean("initialized")){rpc("genesis_wallet_initialize",json("p_initial_gp",0,"p_initial_essence",0));s=rpc("genesis_secure_snapshot",new JSONObject());}
  rpc("genesis_verify_achievements",json("p_request_key",UUID.randomUUID().toString()));
  JSONObject m=rpc("genesis_meta_snapshot",new JSONObject());s=rpc("genesis_secure_snapshot",new JSONObject());
  economy=rpc("genesis_v2_status",new JSONObject());
  // Page through RLS-protected rows; avoid the legacy snapshot's 1000-character ceiling.
  JSONArray rows=new JSONArray();int offset=0;
  while(true){JSONArray batch=arr(api.get("/rest/v1/genesis_characters?select=*&or=(archived.eq.false,selection_state.eq.pending)&order=created_at.desc,registry_id.desc&limit=500&offset="+offset),"items");for(int i=0;i<batch.length();i++)rows.put(batch.getJSONObject(i));if(batch.length()<500)break;offset+=batch.length();}
  JSONObject snap=rpc("genesis_collection_snapshot",json("p_limit",1,"p_history_limit",200));
  JSONArray artwork=arr(api.get("/rest/v1/genesis_character_media?select=registry_id,storage_path,updated_at&limit=1000"),"items");
  JSONArray built=new JSONArray(),waiting=new JSONArray();for(int i=0;i<rows.length();i++){JSONObject row=rows.getJSONObject(i);JSONObject c=new JSONObject(engine.call("nativeReconstruct",row.toString()));if(row.optString("selection_state").equals("pending"))waiting.put(c);else built.put(c);}pending=waiting;
  s.put("wallet",obj(economy,"wallet"));profile=p;secure=s;meta=m;characters=built;history=arr(snap,"history");media=artwork;ready=true;
 }
 private void mutate(String name,JSONObject args,boolean receipt){final JSONObject before=current();if(receipt){try{args.put("p_request_key",UUID.randomUUID().toString());}catch(JSONException ignored){}}task(()->{JSONObject result;try{result=rpc(name,args);}catch(IOException e){if(!receipt)throw e;result=rpc(name,args);}try{refresh();}catch(Exception ex){throw new IOException("The action may have completed. Refresh before trying again. "+ex.getMessage());}return result;},x->{render();JSONObject result=(JSONObject)x;if(result.has("results"))reveal(arr(result,"results"));else if(before!=null&&(name.equals("genesis_character_train")||name.equals("genesis_character_ascend")||name.startsWith("genesis_character_upgrade_"))){JSONObject after=current();if(after!=null)presentation.progression(name.equals("genesis_character_train")?"train":name.equals("genesis_character_ascend")?"evolution":"upgrade",before,after,name.endsWith("_weapon")?"weapon":args.optString("p_slot","weapon"));else alert("Saved to your account.");}else alert("Saved to your account.");});}
 private void login(){body.removeAllViews();nav.removeAllViews();ready=false;status.setText("GENESIS NETWORK");asset(body,"media/branding/genesis-logo.png",150);heading("Enter the Sanctum");note("Your characters. Your chronicles. One account.");if(!Api.configured()){note("Backend not configured. Check SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY in repository Variables, then rebuild.");return;}EditText email=input(body,"Email",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS),pass=input(body,"Password",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);button(body,"Sign in",()->authenticate(email,pass,false));button(body,"Create account",()->authenticate(email,pass,true));note("Confirm your email if requested, then sign in. Sessions are securely stored on this device.");}
 private void authenticate(EditText e,EditText p,boolean signup){String email=e.getText().toString().trim(),password=p.getText().toString();if(email.isEmpty()||password.isEmpty()){alert("Enter your email and password.");return;}task(()->{boolean ok=api.authenticate(email,password,signup);if(ok)refresh();return ok;},x->{p.setText("");if(Boolean.TRUE.equals(x))render();else alert("Check your email for confirmation, then sign in.");});}
 private void logout(){task(()->{api.logout();return null;},x->{profile=new JSONObject();characters=new JSONArray();history=new JSONArray();media=new JSONArray();cache.evictAll();selected="";login();});}
 private JSONObject current(){for(int i=0;i<characters.length();i++){JSONObject c=characters.optJSONObject(i);if(c.optString("serverRegistryId").equals(selected))return c;}return null;}
 private String name(JSONObject c){String n=c.optString("customName","").trim();return n.isEmpty()?"UNNAMED HERO":n;}
 private void gotoPage(String p){page=p;pageSize=30;render();}
 private void render(){body.removeAllViews();nav.removeAllViews();if(!ready){login();return;}JSONObject wallet=obj(secure,"wallet");status.setText(profile.optString("display_name","Summoner")+"  •  "+wallet.optLong("gp")+" GP  •  "+wallet.optLong("essence")+" Essence");for(String label:new String[]{"Home","Collection","Progression","Prompt","More"}){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextSize(10);b.setPadding(0,0,0,0);b.setTextColor(label.equals(page)?gold:muted);b.setBackgroundColor(bg);nav.addView(b,new LinearLayout.LayoutParams(0,dp(54),1));b.setOnClickListener(v->{if(!busy)gotoPage(label);});}switch(page){case "Collection":collection();break;case "Review":review();break;case "Progression":progression();break;case "Prompt":prompt();break;case "Codex":codex();break;case "Daily":daily();break;case "Shop":shop();break;case "Achievements":achievements();break;case "Profile":profilePage();break;case "History":historyPage();break;case "Settings":settings();break;case "Detail":detail();break;case "More":more();break;default:home();}}
 private void more(){heading("Your chronicles");for(String p:new String[]{"Shop","Codex","Daily","Achievements","Profile","History","Settings"})button(body,p,()->gotoPage(p));}
 private void home(){heading("The summoning sanctum");if(pending.length()>0)button(body,"Review pending characters ("+pending.length()+")",()->gotoPage("Review"));JSONObject w=obj(economy,"wallet");note("GP "+w.optLong("gp")+" · Tickets "+w.optInt("tickets")+" · Tokens "+w.optInt("tokens"));sanctum=new SanctumRitualView(this,prefs);body.addView(sanctum,new LinearLayout.LayoutParams(-1,dp(300)));sanctum.setRunning(hasWindowFocus());button(body,"Summon ×1 · 12 GP",()->summon(1)).setEnabled(w.optLong("gp")>=12);button(body,"Summon ×10 · 120 GP",()->summon(10)).setEnabled(w.optLong("gp")>=120);button(body,"Use 1 summon ticket",()->mutate("genesis_v2_summon",json("p_count",1,"p_use_ticket",true),true)).setEnabled(w.optInt("tickets")>=1);button(body,"Use 10 summon tickets",()->mutate("genesis_v2_summon",json("p_count",10,"p_use_ticket",true),true)).setEnabled(w.optInt("tickets")>=10);note("Earn GP and tickets through Daily missions. Summon results give no GP. No purchases or cash rewards.");note("SR+ guaranteed within "+(40-w.optInt("sr_pity"))+" summons. Mythic guaranteed within "+(90-w.optInt("mythic_pity"))+" summons.");note("Next Mythic chance: "+String.format(Locale.US,"%.1f%%",economy.optDouble("mythic_chance")*100));button(body,"Rarity details",()->alert("Common 3★: 60%\nRare 4★: 30%\nSuper Rare 5★: 7%\nEpic 6★: 2.5%\nMythic 7★: 0.5%\n\nBase odds before pity. Mythic chance rises by 0.5 percentage points per summon from summon 70 (1%) to 89 (10.5%); summon 90 guarantees Mythic. SR+ resets SR pity; only Mythic resets Mythic pity. At SR guarantee, the remaining non-Mythic chance is divided SR:Epic 7:2.5. Race is selected equally from eligible races. Both counters are always active, including tickets."));button(body,"Daily missions",()->gotoPage("Daily"));button(body,"Exchange Shop",()->gotoPage("Shop"));}
 private void summon(int n){mutate("genesis_v2_summon",json("p_count",n,"p_use_ticket",false),true);}
 private void reveal(JSONArray rows){
  ArrayList<JSONObject> results=new ArrayList<>();
  for(int i=0;i<rows.length();i++){JSONObject row=rows.optJSONObject(i);if(row==null)continue;for(int j=0;j<pending.length();j++){JSONObject c=pending.optJSONObject(j);if(c.optString("serverRegistryId").equals(row.optString("registry_id"))){results.add(c);break;}}}
  if(results.isEmpty()){alert("Results are saved. Open Review pending characters to choose Keep or Discard.");return;}
  gotoPage("Review");presentation.summon(results);
 }

 private void review(){
  heading("Keep or discard");note("Only characters you keep enter Collection. Unresolved results stay here if you close the app.");
  note("Discard removes the playable character. History and discovery records remain. No refund; pity is unchanged.");
  if(pending.length()==0){note("All results reviewed.");button(body,"Open Collection",()->gotoPage("Collection"));return;}
  note(pending.length()+" pending characters");
  for(int i=0;i<Math.min(pageSize,pending.length());i++){
   JSONObject c=pending.optJSONObject(i);String id=c.optString("serverRegistryId");hero(body,c,false);
   button(body,"Keep · Save to Collection",()->decide(id,true));
   button(body,"Discard",()->new AlertDialog.Builder(this).setTitle("Discard this character?").setMessage(c.optString("race")+" · "+obj(c,"rarity").optString("name")+" · CP "+c.optInt("combatPower")+"\nThis character will not enter Collection. This choice cannot be undone.").setNegativeButton("Cancel",null).setPositiveButton("Discard",(d,w)->decide(id,false)).show());
  }
  if(pageSize<pending.length())button(body,"Load more",()->{pageSize+=30;render();});
 }
 private void decide(String id,boolean keep){
  task(()->{JSONObject args=json("p_registry_id",id,"p_keep",keep);try{rpc("genesis_character_decide",args);}catch(IOException ex){rpc("genesis_character_decide",args);}refresh();return null;},x->{page="Review";render();if(keep)new AlertDialog.Builder(this).setTitle("Saved to Collection").setMessage("You can now name and manage this character.").setNegativeButton("Continue reviewing",null).setPositiveButton("Open character",(d,w)->{selected=id;gotoPage("Detail");}).show();});
 }
 private void hero(LinearLayout parent,JSONObject c,boolean controls){LinearLayout box=card(parent);asset(box,"media/rarities/"+(c.optBoolean("legacy",true)?"":"v2/")+slug(obj(c,"rarity").optString("name"))+".png",prefs.getBoolean("compact",false)?60:85);thumbnail(box,c,prefs.getBoolean("compact",false)?100:180);text(box,(c.optBoolean("legacy",true)?"[Legacy] ":"")+name(c)+(c.optBoolean("favorite")?" ♥":""),20,white);text(box,c.optString("race")+" · "+c.optString("class"),14,muted);text(box,"CP "+c.optInt("combatPower")+" · Lv. "+obj(c,"progression").optInt("level",1),15,gold);if(controls)button(box,"View character",()->{selected=c.optString("serverRegistryId");gotoPage("Detail");});}
 private void collection(){heading("Collection");if(pending.length()>0)button(body,"Review pending characters ("+pending.length()+")",()->gotoPage("Review"));note(characters.length()+" characters");EditText q=input(body,"Search name, race, class or ID",InputType.TYPE_CLASS_TEXT);q.setText(search);button(body,"Apply search",()->{search=q.getText().toString().trim().toLowerCase(Locale.ROOT);pageSize=30;render();});button(body,"Filter: "+filter,()->{String[] options={"All","Favorites","Legacy","Common","Uncommon","Rare","Special Rare","Super Rare","Super Special Rare","Epic","Legendary","Mythical","Primordial","Mythic"};new AlertDialog.Builder(this).setItems(options,(d,i)->{filter=options[i];pageSize=30;render();}).show();});int count=0;for(int i=0;i<characters.length();i++){JSONObject c=characters.optJSONObject(i);boolean matches=filter.equals("All")||(filter.equals("Favorites")?c.optBoolean("favorite"):filter.equals("Legacy")?c.optBoolean("legacy",true):obj(c,"rarity").optString("name").equals(filter));String key=(name(c)+c.optString("race")+c.optString("class")+c.optString("characterId")).toLowerCase(Locale.ROOT);if(matches&&key.contains(search)){if(count<pageSize)hero(body,c,true);count++;}}if(count==0)note("No matching characters.");if(count>pageSize)button(body,"Load more",()->{pageSize+=30;render();});}
 private void selectCharacter(){String[] labels=new String[characters.length()];for(int i=0;i<labels.length;i++){JSONObject c=characters.optJSONObject(i);labels[i]=name(c)+" · "+c.optString("characterId");}if(labels.length==0){alert("Summon a character first.");return;}new AlertDialog.Builder(this).setTitle("Choose a character").setItems(labels,(d,i)->{selected=characters.optJSONObject(i).optString("serverRegistryId");render();}).show();}
 private void detail(){JSONObject c=current();if(c==null){heading("Choose a character");button(body,"Open collection",()->gotoPage("Collection"));return;}hero(body,c,false);artwork(c);button(body,c.optBoolean("favorite")?"Remove favorite":"Favorite",()->mutate("genesis_character_set_favorite",json("p_registry_id",selected,"p_favorite",!c.optBoolean("favorite")),false));button(body,"Rename",()->{EditText e=new EditText(this);e.setSingleLine(true);e.setText(c.optString("customName"));e.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(48)});new AlertDialog.Builder(this).setTitle("Character name").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->mutate("genesis_character_set_name",json("p_registry_id",selected,"p_custom_name",e.getText().toString()),false)).show();});button(body,"Progression",()->gotoPage("Progression"));button(body,"Prompt Studio",()->gotoPage("Prompt"));for(String k:new String[]{"characterId","seed","raceCategory","gender","age","origin","subclass","faction","affinity","title","ability","ultimate","passive","powerType","magicType","trait","personality","alignment","weapon","weaponCategory","weaponEffect"})note(k.replaceAll("([a-z])([A-Z])","$1 $2")+": "+c.optString(k));text(body,"Character stats",20,gold);try{JSONObject stats=new JSONObject(engine.call("nativeStats",c.toString()));for(String key:new String[]{"STR","AGI","INT","DEF","VIT","LCK"})note(key+": "+stats.optInt(key));}catch(JSONException ignored){}text(body,"Equipment",20,gold);JSONObject eq=obj(c,"equipment");for(String k:new String[]{"armor","accessory","relic","artifact"}){JSONObject e=obj(eq,k);note(k+": "+e.optString("name")+" +"+e.optInt("upgrade")+" · "+obj(e,"rarity").optString("name"));}note(c.optString("lore"));button(body,"Archive character",()->new AlertDialog.Builder(this).setTitle("Archive this character?").setMessage("It will leave your active Collection. This edition has no restore control.").setNegativeButton("Keep",null).setPositiveButton("Archive",(d,w)->{page="Collection";mutate("genesis_character_archive",json("p_registry_id",selected),false);}).show());}
 private void progression(){heading("Character progression");button(body,"Choose character",this::selectCharacter);JSONObject c=current();if(c==null){note("Choose a Collection character to train or upgrade.");return;}hero(body,c,false);JSONObject p=obj(c,"progression");String[] stages={"Base","Awakened","Ascended","Transcendent"};note(stages[Math.min(3,p.optInt("stage"))]+" · EXP "+p.optInt("xp"));int lv=p.optInt("level",1);note("Next training cost: "+Math.max(12,Math.round(10+lv*2.4))+" Essence");button(body,"Train +1",()->mutate("genesis_character_train",json("p_registry_id",selected,"p_levels",1),true)).setEnabled(lv<100);button(body,"Train ×5",()->mutate("genesis_character_train",json("p_registry_id",selected,"p_levels",5),true)).setEnabled(lv<100);note("Evolution: Awakened Lv25 / 250 Essence; Ascended Lv50 / 600; Transcendent Lv80 / 1200.");button(body,"Advance evolution",()->mutate("genesis_character_ascend",json("p_registry_id",selected),true)).setEnabled(p.optInt("stage")<3);int w=c.optInt("weaponUpgrade");button(body,"Weapon +"+w+" · Upgrade ("+(45+w*35+w*w*4)+" Essence)",()->mutate("genesis_character_upgrade_weapon",json("p_registry_id",selected),true)).setEnabled(w<10);for(String slot:new String[]{"armor","accessory","relic","artifact"}){JSONObject e=obj(obj(c,"equipment"),slot);int level=e.optInt("upgrade"),stars=obj(e,"rarity").optInt("stars",1);long cost=Math.round((30+level*26+level*level*3)*(1+(stars-1)*.08));note(e.optString("name"));button(body,slot+" +"+level+" · Upgrade ("+cost+" Essence)",()->mutate("genesis_character_upgrade_equipment",json("p_registry_id",selected,"p_slot",slot),true)).setEnabled(level<10);}}
 private void prompt(){heading("Prompt Studio");button(body,"Choose character",this::selectCharacter);JSONObject c=current();if(c==null){note("Choose a character from Collection.");return;}text(body,name(c),22,white);note("Character Splash Art · 3:4 · compact premium prompt");String prompt=engine.call("nativePrompt",c.toString());TextView output=text(card(body),prompt,14,white);output.setTextIsSelectable(true);button(body,"Copy prompt",()->{android.content.ClipboardManager clipboard=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);clipboard.setPrimaryClip(ClipData.newPlainText("Genesis Splash Art",prompt));alert("Prompt copied.");});note("Generate the artwork using your image tool, then attach the result to this character.");button(body,"Upload artwork",()->{uploadId=selected;uploadPrompt=prompt;Intent pick=new Intent(Intent.ACTION_OPEN_DOCUMENT);pick.setType("image/*");pick.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"image/png","image/jpeg","image/webp"});pick.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(pick,64);});artwork(c);}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request!=64||result!=RESULT_OK||data==null||data.getData()==null)return;android.net.Uri uri=data.getData();String id=uploadId,prompt=uploadPrompt;if(id.isEmpty())return;task(()->{String mime=getContentResolver().getType(uri);if(!Arrays.asList("image/png","image/jpeg","image/webp").contains(mime))throw new IOException("Use PNG, JPEG or WebP.");byte[] content;try(InputStream in=getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("Unable to open image");content=bytes(in,10485760);}BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(content,0,content.length,bounds);if(bounds.outWidth<=0)throw new IOException("Invalid image file");String path=profile.getString("user_id")+"/"+id+"/primary";api.upload("/storage/v1/object/genesis-character-art/"+path,content,mime);rpc("genesis_character_media_upsert",json("p_registry_id",id,"p_storage_path",path,"p_mime_type",mime,"p_file_size",content.length,"p_prompt_snapshot",prompt));refresh();return null;},x->{render();alert("Artwork saved to this character.");});}
 private void artwork(JSONObject c){String id=c.optString("serverRegistryId"),path="";for(int i=0;i<media.length();i++){JSONObject m=media.optJSONObject(i);if(m.optString("registry_id").equals(id)){path=m.optString("storage_path");break;}}if(path.isEmpty()){note("Artwork not submitted. Race emblem is shown.");return;}final String storagePath=path;button(body,"View submitted artwork",()->task(()->{JSONObject signed=api.storage("/storage/v1/object/sign/genesis-character-art/"+storagePath,json("expiresIn",300));String part=signed.optString("signedURL",signed.optString("signedUrl"));if(!part.startsWith("/object/"))throw new IOException("Unexpected artwork response");java.net.HttpURLConnection conn=(java.net.HttpURLConnection)new java.net.URL(BuildConfig.SUPABASE_URL.replaceAll("/+$","")+"/storage/v1"+part).openConnection();conn.setInstanceFollowRedirects(false);conn.setConnectTimeout(15000);conn.setReadTimeout(20000);try(InputStream in=conn.getInputStream()){byte[] bytes=bytes(in,10485760);BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);o.inSampleSize=1;while(o.outWidth/o.inSampleSize>1600||o.outHeight/o.inSampleSize>1600)o.inSampleSize*=2;o.inJustDecodeBounds=false;return BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);}finally{conn.disconnect();}},x->{ImageView v=new ImageView(this);v.setAdjustViewBounds(true);v.setImageBitmap((Bitmap)x);new AlertDialog.Builder(this).setTitle(name(c)).setView(v).setPositiveButton("Close",null).show();status.setText("Artwork loaded");}));}

 private void thumbnail(LinearLayout box,JSONObject character,int height){
  JSONObject found=null;for(int i=0;i<media.length();i++){JSONObject m=media.optJSONObject(i);if(m.optString("registry_id").equals(character.optString("serverRegistryId"))){found=m;break;}}
  if(found==null){asset(box,"media/races/"+slug(character.optString("baseRace","unknown"))+".png",height);return;}
  final JSONObject item=found;final String key=item.optString("storage_path")+item.optString("updated_at");
  ImageView view=new ImageView(this);view.setScaleType(ImageView.ScaleType.FIT_CENTER);view.setContentDescription(name(character)+" artwork");box.addView(view,new LinearLayout.LayoutParams(-1,dp(height)));Bitmap cached=cache.get(key);if(cached!=null){view.setImageBitmap(cached);return;}
  images.execute(()->{try{Bitmap bitmap=downloadArtwork(item.getString("storage_path"),800);if(bitmap!=null){cache.put(key,bitmap);runOnUiThread(()->{if(!isDestroyed())view.setImageBitmap(bitmap);});}}catch(Exception ex){runOnUiThread(()->{if(!isDestroyed())view.setContentDescription("Artwork unavailable. Refresh to retry.");});}});
 }
 private Bitmap downloadArtwork(String path,int maxSide)throws Exception {
  JSONObject signed=api.storage("/storage/v1/object/sign/genesis-character-art/"+path,json("expiresIn",300));String suffix=signed.optString("signedURL",signed.optString("signedUrl"));if(!suffix.startsWith("/object/"))throw new IOException("Unexpected artwork response");
  java.net.HttpURLConnection connection=(java.net.HttpURLConnection)new java.net.URL(BuildConfig.SUPABASE_URL.replaceAll("/+$","")+"/storage/v1"+suffix).openConnection();connection.setInstanceFollowRedirects(false);connection.setConnectTimeout(15000);connection.setReadTimeout(20000);
  try(InputStream in=connection.getInputStream()){byte[] data=bytes(in,10485760);BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(data,0,data.length,o);o.inSampleSize=1;while(o.outWidth/o.inSampleSize>maxSide||o.outHeight/o.inSampleSize>maxSide)o.inSampleSize*=2;o.inJustDecodeBounds=false;return BitmapFactory.decodeByteArray(data,0,data.length,o);}finally{connection.disconnect();}
 }

 private void codex(){heading("Codex");JSONArray entries=arr(meta,"codex");note(entries.length()+" discoveries verified by the server");Set<String> discovered=new HashSet<>();for(int i=0;i<entries.length();i++){JSONObject e=entries.optJSONObject(i);discovered.add(e.optString("codex_type")+"|"+e.optString("entry_key"));}button(body,"All discoveries",()->{StringBuilder b=new StringBuilder();for(int i=0;i<entries.length();i++){JSONObject e=entries.optJSONObject(i);b.append(e.optString("codex_type")).append(" · ").append(e.optString("entry_key")).append(" ×").append(e.optInt("times_obtained")).append('\n');}alert(b.length()==0?"No discoveries yet.":b.toString());});JSONArray races=arr(obj(catalog,"data"),"races");for(int i=0;i<races.length();i++){String race=races.optJSONArray(i).optString(0);boolean known=discovered.contains("race|"+race);LinearLayout box=card(body);asset(box,"media/races/"+(known?slug(race):"unknown")+".png",85);text(box,race+" · "+obj(catalog,"families").optString(race),17,gold);text(box,known?"Discovered":"Not discovered",13,muted);}}
 private void achievements(){heading("Achievements");Set<String> unlocked=new HashSet<>();JSONArray earned=arr(meta,"achievements");for(int i=0;i<earned.length();i++)unlocked.add(earned.optJSONObject(i).optString("achievement_id"));note(unlocked.size()+" unlocked · "+obj(meta,"profile").optInt("achievement_points")+" AP. Legacy achievements retain earned rewards; retired targets are marked below.");JSONArray defs=arr(catalog,"achievements");for(int i=0;i<defs.length();i++){JSONObject a=defs.optJSONObject(i);LinearLayout box=card(body);text(box,a.optString("name")+(unlocked.contains(a.optString("id"))?" ✓":""),18,gold);text(box,a.optString("desc"),14,muted);text(box,a.optInt("ap")+" AP · "+reward(obj(a,"reward")),13,white);JSONArray progress=obj(meta,"achievement_progress").optJSONArray(a.optString("id"));if(a.optBoolean("legacy")&&!unlocked.contains(a.optString("id")))text(box,"Retired target · historical progress retained",13,muted);if(progress!=null)text(box,progress.optLong(0)+" / "+progress.optLong(1),13,muted);}}
 private String reward(JSONObject r){List<String> a=new ArrayList<>();for(String k:new String[]{"gp","essence","xp"})if(r.optLong(k)>0)a.add(r.optLong(k)+" "+k.toUpperCase(Locale.ROOT));return android.text.TextUtils.join(" + ",a);}
 private void daily(){heading("Daily rewards");note("Server date: "+economy.optString("server_date")+" · Resets at 00:00 UTC. GP and tickets do not expire. No streak penalty.");String[] ids={"checkin","summon1","summon3","train1","upgrade1"};String[] titles={"Daily check-in","Summon 1 character","Summon 3 characters","Train once","Upgrade once"};String[] rewards={"60 GP + 50 Essence + 10 Tokens + 1 Ticket","12 GP","24 GP","12 GP + 15 Essence","12 GP + 20 Essence"};JSONArray claims=arr(economy,"claims");for(int i=0;i<ids.length;i++){final String id=ids[i];int target=i==2?3:1;boolean claimed=false;for(int j=0;j<claims.length();j++)if(id.equals(claims.optString(j)))claimed=true;LinearLayout box=card(body);text(box,titles[i],18,gold);text(box,rewards[i],14,muted);int progress=obj(economy,"progress").optInt(id);text(box,Math.min(progress,target)+" / "+target,13,white);button(box,claimed?"Claimed":"Claim reward",()->mutate("genesis_v2_claim",json("p_mission",id),true)).setEnabled(!claimed&&progress>=target);}button(body,"Exchange Shop",()->gotoPage("Shop"));}
 private void shop(){heading("Exchange Shop");int tokens=obj(economy,"wallet").optInt("tokens");note(tokens+" Genesis Tokens · Earned through Daily rewards");note("Fixed items and prices. No random boxes or chance boosts.");String[] ids={"essence50","essence150"};int[] costs={5,12},amounts={50,150};for(int i=0;i<ids.length;i++){final String id=ids[i];final int cost=costs[i],amount=amounts[i];button(body,amount+" Essence · "+cost+" Tokens",()->new AlertDialog.Builder(this).setTitle("Confirm exchange").setMessage("Exchange "+cost+" Tokens for "+amount+" Essence?").setNegativeButton("Cancel",null).setPositiveButton("Exchange",(d,w)->mutate("genesis_v2_shop_buy",json("p_item",id),true)).show()).setEnabled(tokens>=cost);}}
 private void profilePage(){heading("Summoner profile");note(profile.optString("player_id"));EditText name=input(body,"Display name",InputType.TYPE_CLASS_TEXT);name.setText(profile.optString("display_name"));name.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(28)});button(body,"Save display name",()->mutate("genesis_profile_ensure",json("p_display_name",name.getText().toString()),false));JSONObject p=obj(meta,"profile");note("Level "+p.optInt("summoner_level",1)+" · Lifetime EXP "+p.optLong("summoner_xp"));note(p.optInt("achievement_points")+" AP · "+p.optString("achievement_rank"));JSONObject stats=obj(meta,"stats");for(String k:new String[]{"total_summons","ten_pulls","highest_combat_power","highest_weapon_power","daily_mission_claims","perfect_daily_days","full_login_cycles"})note(k.replace('_',' ')+": "+stats.optLong(k));button(body,"Sign out",this::logout);}
 private void historyPage(){heading("History & economy ledger");note("Latest 200 characters and 10 economy events");JSONArray ledger=arr(secure,"ledger");for(int i=0;i<ledger.length();i++){JSONObject e=ledger.optJSONObject(i);text(card(body),e.optString("event_type")+"\nGP "+e.optLong("gp_delta")+" · Essence "+e.optLong("essence_delta")+"\n"+e.optString("created_at"),14,muted);}for(int i=0;i<Math.min(pageSize,history.length());i++){JSONObject h=history.optJSONObject(i);LinearLayout box=card(body);asset(box,"media/rarities/"+(h.optString("seed").startsWith("G165-")?"v2/":"")+slug(h.optString("rarity_name"))+".png",70);text(box,h.optString("character_id")+"\n"+h.optString("created_at")+(h.optBoolean("archived")?"\nArchived":""),14,white);}if(pageSize<history.length())button(body,"Load more",()->{pageSize+=30;render();});}
 private void volume(String label,String key,int defaultValue){
  TextView value=text(body,label+": "+prefs.getInt(key,defaultValue)+"%",14,muted);
  SeekBar bar=new SeekBar(this);bar.setMax(100);bar.setProgress(prefs.getInt(key,defaultValue));bar.setContentDescription(label);body.addView(bar,new LinearLayout.LayoutParams(-1,dp(48)));
  bar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int progress,boolean fromUser){value.setText(label+": "+progress+"%");if(fromUser){prefs.edit().putInt(key,progress).apply();audio.settingsChanged();}}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});
 }
 private void settings(){heading("Settings");toggle("Background music","music",true);volume("Music volume","musicVolume",35);toggle("Sound effects","sound",true);volume("Effects volume","sfxVolume",65);button(body,"Preview rarity effects",()->new AlertDialog.Builder(this).setTitle("Choose rarity effect").setItems(new String[]{"Common","Rare","Super Rare","Epic","Mythic"},(d,i)->presentation.preview(new int[]{0,2,4,6,8}[i])).show());toggle("Reduce motion","reduceMotion",false);toggle("Compact collection","compact",false);button(body,"Refresh account",()->task(()->{refresh();return null;},x->render()));button(body,"Sign out",this::logout);note("Genesis 17.0 · Five-tier economy\nProgress and artwork are stored in your online account. This app stores only encrypted session tokens and display preferences locally.");}
}
