package com.genesis.gacha;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import android.text.InputType;
import org.json.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

public final class MainActivity extends Activity {
 private final Api api=Api.INSTANCE;
 private final ExecutorService worker=Executors.newSingleThreadExecutor();
 private final ExecutorService localImages=Executors.newFixedThreadPool(2);
 private final ExecutorService images=Executors.newFixedThreadPool(2);
 private final android.util.LruCache<String,Bitmap> cache=new android.util.LruCache<String,Bitmap>(16*1024*1024){protected int sizeOf(String k,Bitmap b){return b.getByteCount();}};
 private CharacterEngine engine;
 private GenesisAudio audio;
 private SanctumRitualView sanctum;
 private GenesisPresentation presentation;
 private LinearLayout headerBar,loadingLayer;
 private Button backButton;
 private LobbyBackdrop livingScene;
 private TextView loadingText;
 private ProgressBar loadingSpinner;
 private boolean startup=true;
 private SanctumPanel embeddedSanctum;
 private final ArrayList<JSONObject> activeSummons=new ArrayList<>();
 private final Map<String,String> summonChoices=new HashMap<>();
 private JSONObject catalog=new JSONObject(),profile=new JSONObject(),secure=new JSONObject(),meta=new JSONObject(),economy=new JSONObject();
 private JSONArray pending=new JSONArray(),characters=new JSONArray(),history=new JSONArray(),media=new JSONArray();
 private ScrollView contentScroll,navScroll;private LinearLayout root,body,nav;private TextView status;
 private String page="Lobby",selected="",search="",filter="All",uploadId="",uploadPrompt="";
 private int pageSize=30;private boolean busy=false,ready=false;private android.content.SharedPreferences prefs;
 private final int bg=PixelFrame.INK,panel=PixelFrame.PANEL,gold=PixelFrame.GOLD,muted=PixelFrame.MUTED,white=PixelFrame.TEXT;
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("presentation",MODE_PRIVATE);audio=new GenesisAudio(this,prefs);presentation=new GenesisPresentation(this,prefs,audio,this::asset);api.attach(this);if(b!=null){page=b.getString("page","Lobby");selected=b.getString("selected","");uploadId=b.getString("uploadId","");uploadPrompt=b.getString("uploadPrompt","");}shell();task(()->{engine=new CharacterEngine(assetText("engine.js"));catalog=new JSONObject(assetText("catalog.json"));if(api.signedIn())refresh();return null;},x->{if(api.signedIn()&&ready)render();else login();});}
 @Override public void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putString("page",page);b.putString("selected",selected);b.putString("uploadId",uploadId);b.putString("uploadPrompt",uploadPrompt);}
 @Override public void onResume(){super.onResume();if(sanctum!=null)sanctum.setRunning(true);if(audio!=null)audio.resume();if(livingScene!=null&&page.equals("Lobby"))livingScene.start(!prefs.getBoolean("reduceMotion",false));if(embeddedSanctum!=null)embeddedSanctum.resume();if(presentation!=null)presentation.resume();}
 @Override public void onPause(){if(sanctum!=null)sanctum.setRunning(false);if(presentation!=null)presentation.pause();if(audio!=null)audio.pause();if(livingScene!=null)livingScene.stop();if(embeddedSanctum!=null)embeddedSanctum.pause();super.onPause();}
 @Override public void onWindowFocusChanged(boolean focus){super.onWindowFocusChanged(focus);if(sanctum!=null)sanctum.setRunning(focus);}
 @Override public void onDestroy(){if(sanctum!=null)sanctum.setRunning(false);if(presentation!=null)presentation.close();if(audio!=null)audio.close();if(livingScene!=null)livingScene.stop();worker.shutdown();localImages.shutdownNow();images.shutdownNow();cache.evictAll();super.onDestroy();}
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 private JSONObject obj(JSONObject p,String k){JSONObject o=p.optJSONObject(k);return o==null?new JSONObject():o;}
 private JSONArray arr(JSONObject p,String k){JSONArray a=p.optJSONArray(k);return a==null?new JSONArray():a;}
 private JSONObject json(Object... pairs){JSONObject o=new JSONObject();try{for(int i=0;i<pairs.length;i+=2)o.put((String)pairs[i],pairs[i+1]);}catch(JSONException e){throw new IllegalArgumentException(e);}return o;}
 private String assetText(String name)throws Exception {try(InputStream in=getAssets().open(name)){return new String(bytes(in,2000000),java.nio.charset.StandardCharsets.UTF_8);}}
 private static byte[] bytes(InputStream in,int max)throws Exception {ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){if(out.size()+n>max)throw new IOException("File is too large");out.write(b,0,n);}return out.toByteArray();}
 private void shell(){
  root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);
  root.setPadding(dp(8),dp(4),dp(8),dp(4));
  root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(i.getSystemWindowInsetLeft()+dp(8),i.getSystemWindowInsetTop()+dp(4),i.getSystemWindowInsetRight()+dp(8),i.getSystemWindowInsetBottom()+dp(4));return i;});FrameLayout layers=new FrameLayout(this);layers.addView(root,new FrameLayout.LayoutParams(-1,-1));setContentView(layers);
  loadingLayer=new LinearLayout(this);loadingLayer.setOrientation(LinearLayout.VERTICAL);loadingLayer.setGravity(Gravity.CENTER);loadingLayer.setBackground(new LobbyBackdrop());loadingLayer.setClickable(true);loadingLayer.setFocusable(true);loadingLayer.setVisibility(View.GONE);layers.addView(loadingLayer,new FrameLayout.LayoutParams(-1,-1));
  TextView loadingBrand=new TextView(this);PixelFrame.type(loadingBrand);loadingBrand.setText("G E N E S I S");loadingBrand.setTextSize(28);loadingBrand.setTextColor(gold);loadingLayer.addView(loadingBrand);
  loadingSpinner=new ProgressBar(this);loadingSpinner.setIndeterminate(true);loadingSpinner.setIndeterminateTintList(android.content.res.ColorStateList.valueOf(gold));LinearLayout.LayoutParams spinnerParams=new LinearLayout.LayoutParams(dp(44),dp(44));spinnerParams.setMargins(0,dp(20),0,dp(12));loadingLayer.addView(loadingSpinner,spinnerParams);loadingText=new TextView(this);PixelFrame.type(loadingText);loadingText.setTextSize(13);loadingLayer.addView(loadingText);
  LinearLayout header=new LinearLayout(this);headerBar=header;header.setGravity(Gravity.CENTER_VERTICAL);header.setBackground(new PixelFrame(this,panel,gold));header.setPadding(dp(12),dp(4),dp(12),dp(4));root.addView(header,new LinearLayout.LayoutParams(-1,dp(44)));
  backButton=new Button(this);PixelFrame.type(backButton);backButton.setText("‹ Back");backButton.setTextSize(11);backButton.setAllCaps(false);backButton.setPadding(0,0,0,0);backButton.setBackground(PixelFrame.button(this));header.addView(backButton,new LinearLayout.LayoutParams(dp(66),dp(44)));backButton.setOnClickListener(v->{if(!busy)gotoPage("Lobby");});

  status=new TextView(this);PixelFrame.type(status);status.setText("Connecting…");status.setTextSize(12);status.setTextColor(muted);status.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);status.setAccessibilityLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);header.addView(status,new LinearLayout.LayoutParams(0,-1,1));
  LinearLayout workspace=new LinearLayout(this);root.addView(workspace,new LinearLayout.LayoutParams(-1,0,1));
  navScroll=new ScrollView(this);navScroll.setFillViewport(true);workspace.addView(navScroll,new LinearLayout.LayoutParams(dp(100),-1));nav=new LinearLayout(this);nav.setOrientation(LinearLayout.VERTICAL);nav.setPadding(0,dp(6),dp(8),0);navScroll.addView(nav);
  contentScroll=new ScrollView(this);contentScroll.setFillViewport(true);workspace.addView(contentScroll,new LinearLayout.LayoutParams(0,-1,1));body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(6),dp(8),dp(6),dp(8));contentScroll.addView(body);
 }

 private TextView text(LinearLayout p,String s,int size,int color){TextView v=new TextView(this);PixelFrame.type(v);v.setText(s);v.setTextSize(Math.max(11,size-3));v.setTextColor(color);v.setPadding(0,dp(3),0,dp(3));p.addView(v,new LinearLayout.LayoutParams(-1,-2));return v;}

 private void note(String s){text(body,s,14,muted);}
 private void heading(String s){TextView v=text(body,s.toUpperCase(Locale.ROOT),20,gold);v.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);}

 private LinearLayout card(LinearLayout p){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackground(new PixelFrame(this,panel,gold));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(dp(3),dp(4),dp(3),dp(4));p.addView(c,lp);return c;}

 private Button button(LinearLayout p,String label,Runnable click){Button b=new Button(this);PixelFrame.type(b);b.setText(label);b.setAllCaps(false);b.setTextSize(11);b.setGravity(Gravity.CENTER);b.setPadding(dp(6),dp(2),dp(6),dp(2));b.setBackground(PixelFrame.button(this));if(!prefs.getBoolean("reduceMotion",false))PixelFrame.pressMotion(b);b.setMinHeight(dp(44));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(dp(2),dp(2),dp(2),dp(2));p.addView(b,lp);b.setOnClickListener(v->{if(!busy)click.run();});return b;}

 private EditText input(LinearLayout p,String hint,int type){EditText e=new EditText(this);PixelFrame.type(e);e.setHint(hint);e.setHintTextColor(muted);e.setInputType(type);e.setSingleLine(true);e.setTextSize(14);e.setPadding(dp(12),dp(8),dp(12),dp(8));e.setBackground(new PixelFrame(this,bg,0xff716749));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(50));lp.setMargins(0,dp(4),0,dp(4));p.addView(e,lp);return e;}

 private void toggle(String label,String key,boolean defaultValue){Switch s=new Switch(this);s.setText(label);s.setTextColor(white);s.setMinHeight(dp(52));s.setChecked(prefs.getBoolean(key,defaultValue));body.addView(s);s.setOnCheckedChangeListener((v,on)->{prefs.edit().putBoolean(key,on).apply();audio.settingsChanged();});}
 private void alert(String s){if(!isFinishing())new AlertDialog.Builder(this).setMessage(s).setPositiveButton("OK",null).show();}
 private String slug(String s){return s.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-").replaceAll("^-|-$","");}
 private void asset(LinearLayout p,String path,int height){if(path.startsWith("media/rarities/v2/")){String key=path.substring(path.lastIndexOf('/')+1).replace(".png","");String[] keys={"common","rare","super-rare","epic","mythic"};int tier=0;for(int i=0;i<keys.length;i++)if(keys[i].equals(key))tier=i;p.addView(new RarityBadgeView(this,tier),new LinearLayout.LayoutParams(-1,dp(Math.max(36,height))));return;}ImageView v=new ImageView(this);v.setScaleType(ImageView.ScaleType.FIT_CENTER);v.setContentDescription(path);p.addView(v,new LinearLayout.LayoutParams(-1,dp(height)));loadLocalImage(v,path);}
 private Bitmap decodeLocal(String path)throws IOException{
  Bitmap known=cache.get(path);if(known!=null)return known;
  BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;
  try(InputStream in=getAssets().open(path)){BitmapFactory.decodeStream(in,null,options);}
  if(options.outWidth<=0||options.outHeight<=0)throw new IOException("Invalid image: "+path);
  options.inSampleSize=1;while(options.outWidth/options.inSampleSize>800||options.outHeight/options.inSampleSize>800)options.inSampleSize*=2;
  options.inJustDecodeBounds=false;Bitmap bitmap;
  try(InputStream in=getAssets().open(path)){bitmap=BitmapFactory.decodeStream(in,null,options);}
  if(bitmap==null)throw new IOException("Could not decode: "+path);
  cache.put(path,bitmap);return bitmap;
 }
 private Bitmap imageMessage(String message){
  Bitmap b=Bitmap.createBitmap(320,100,Bitmap.Config.ARGB_8888);Canvas canvas=new Canvas(b);Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);paint.setColor(gold);paint.setTextSize(18);paint.setTextAlign(Paint.Align.CENTER);canvas.drawText(message,160,55,paint);return b;
 }
 private void loadLocalImage(ImageView view,String path){
  Bitmap known=cache.get(path);if(known!=null){view.setImageBitmap(known);return;}
  view.setImageBitmap(imageMessage("Loading image…"));
  localImages.execute(()->{Bitmap bitmap=null;String failure=null;
   try{bitmap=decodeLocal(path);}catch(Exception ex){failure=path+": "+ex.getClass().getSimpleName();android.util.Log.w("GenesisAssets",failure,ex);if(path.startsWith("media/races/")&&!path.endsWith("/unknown.png"))try{bitmap=decodeLocal("media/races/unknown.png");}catch(Exception ignored){}}
   final Bitmap result=bitmap;final String error=failure;
   runOnUiThread(()->{if(isDestroyed())return;view.setImageBitmap(result==null?imageMessage("Image unavailable"):result);view.setContentDescription(error==null?path:"Image unavailable: "+path);view.requestLayout();view.invalidate();});
  });
 }
 private void checkBundledImages(){
  task(()->{JSONObject manifest=new JSONObject(assetText("image-manifest.json"));JSONArray paths=manifest.names();int ok=0;StringBuilder failed=new StringBuilder();for(int i=0;paths!=null&&i<paths.length();i++){String path=paths.getString(i);try{decodeLocal(path);ok++;}catch(Exception ex){failed.append("\n").append(path);}}return ok+" bundled images decoded."+(failed.length()==0?"\nAll required images are readable in this APK.":"\nMissing or unreadable:"+failed);},x->alert(String.valueOf(x)));
 }

 interface Work{Object run()throws Exception;}interface Done{void run(Object value)throws Exception;}
 private void task(Work work,Done done){if(busy)return;busy=true;status.setText("Connecting to Genesis…");showLoading();worker.execute(()->{try{Object x=work.run();runOnUiThread(()->{if(isDestroyed())return;busy=false;hideLoading();try{done.run(x);}catch(Exception e){alert("Could not display the response. Refresh to reload.");}});}catch(Exception e){runOnUiThread(()->{if(isDestroyed())return;busy=false;hideLoading();if(!api.signedIn())login();else if(!ready){body.removeAllViews();heading("Connection needs attention");note("Check your connection and the existing Genesis backend configuration, then retry.");button(body,"Try again",()->task(()->{refresh();return null;},x->render()));button(body,"Sign out",this::logout);}status.setText("Connection interrupted");alert(e.getMessage()==null?"Request failed. Please retry.":e.getMessage());});}});}
 private JSONObject rpc(String name,JSONObject args)throws Exception{return api.rpc(name,args);}
 private void refresh()throws Exception{
  JSONObject p=rpc("genesis_profile_ensure",new JSONObject());JSONObject s=rpc("genesis_secure_snapshot",new JSONObject());
  if(!s.optBoolean("initialized")){rpc("genesis_wallet_initialize",json("p_initial_gp",0,"p_initial_essence",0));s=rpc("genesis_secure_snapshot",new JSONObject());}
  rpc("genesis_verify_achievements",json("p_request_key",UUID.randomUUID().toString()));
  JSONObject m=rpc("genesis_meta_snapshot",new JSONObject());s=rpc("genesis_secure_snapshot",new JSONObject());
  economy=rpc("genesis_v2_status",new JSONObject());
  // Page through RLS-protected rows; avoid the legacy snapshot's 1000-character ceiling.
  JSONArray rows=new JSONArray();int offset=0;
  while(true){JSONArray batch=arr(api.get("/rest/v1/genesis_characters?select=*&or=(archived.eq.false,selection_state.eq.pending)&order=created_at.desc,registry_id.desc&limit=500&offset="+offset),"items");for(int i=0;i<batch.length();i++)rows.put(batch.getJSONObject(i));if(batch.length()<500)break;offset+=batch.length();}
  JSONObject snap=rpc("genesis_collection_snapshot",json("p_limit",1,"p_history_limit",200));
  JSONArray artwork=arr(api.get("/rest/v1/genesis_character_media?select=registry_id,storage_path,updated_at&limit=1000"),"items");
  JSONArray built=new JSONArray(),waiting=new JSONArray();for(int i=0;i<rows.length();i++){JSONObject row=rows.getJSONObject(i);JSONObject c=new JSONObject(engine.call("nativeReconstruct",row.toString()));if(row.optString("selection_state").equals("pending"))waiting.put(c);else built.put(c);}pending=waiting;
  s.put("wallet",obj(economy,"wallet"));profile=p;secure=s;meta=m;characters=built;history=arr(snap,"history");media=artwork;ready=true;
 }
 private void mutate(String name,JSONObject args,boolean receipt){final JSONObject before=current();if(receipt){try{args.put("p_request_key",UUID.randomUUID().toString());}catch(JSONException ignored){}}task(()->{JSONObject result;try{result=rpc(name,args);}catch(IOException e){if(!receipt)throw e;result=rpc(name,args);}try{refresh();}catch(Exception ex){throw new IOException("The action may have completed. Refresh before trying again. "+ex.getMessage());}return result;},x->{JSONObject result=(JSONObject)x;if(result.has("results")){reveal(arr(result,"results"));return;}render();if(before!=null&&(name.equals("genesis_character_train")||name.equals("genesis_character_ascend")||name.startsWith("genesis_character_upgrade_"))){JSONObject after=current();if(after!=null)presentation.progression(name.equals("genesis_character_train")?"train":name.equals("genesis_character_ascend")?"evolution":"upgrade",before,after,name.endsWith("_weapon")?"weapon":args.optString("p_slot","weapon"));else alert("Saved to your account.");}else alert("Saved to your account.");});}
 private void login(){headerBar.setVisibility(View.VISIBLE);backButton.setVisibility(View.GONE);root.setBackgroundColor(bg);body.removeAllViews();nav.removeAllViews();navScroll.setVisibility(View.GONE);ready=false;status.setText("ACCOUNT ACCESS");LinearLayout saved=body;LinearLayout[] panes=workspacePanels();asset(panes[0],"media/branding/genesis-logo.png",145);text(panes[0],"CHARACTER CHRONICLES",18,gold);text(panes[0],"Your characters. Your chronicles. One account.",14,muted);body=panes[1];try{heading("Enter the Sanctum");if(!Api.configured()){note("Backend not configured. Check SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY in repository Variables, then rebuild.");return;}EditText email=input(body,"Email",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS),pass=input(body,"Password",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);button(body,"Sign in",()->authenticate(email,pass,false));button(body,"Create account",()->authenticate(email,pass,true));note("Confirm your email if requested, then sign in. Sessions are securely stored on this device.");}finally{body=saved;}}

 private void authenticate(EditText e,EditText p,boolean signup){String email=e.getText().toString().trim(),password=p.getText().toString();if(email.isEmpty()||password.isEmpty()){alert("Enter your email and password.");return;}task(()->{boolean ok=api.authenticate(email,password,signup);if(ok)refresh();return ok;},x->{p.setText("");if(Boolean.TRUE.equals(x)){page="Lobby";render();}else alert("Check your email for confirmation, then sign in.");});}
 private void logout(){task(()->{api.logout();return null;},x->{profile=new JSONObject();characters=new JSONArray();history=new JSONArray();media=new JSONArray();cache.evictAll();selected="";activeSummons.clear();summonChoices.clear();pending=new JSONArray();page="Lobby";login();});}
 private JSONObject current(){for(int i=0;i<characters.length();i++){JSONObject c=characters.optJSONObject(i);if(c.optString("serverRegistryId").equals(selected))return c;}return null;}
 private String name(JSONObject c){String n=c.optString("customName","").trim();return n.isEmpty()?"UNNAMED HERO":n;}
 private void gotoPage(String p){page=p;pageSize=30;render();contentScroll.post(()->contentScroll.scrollTo(0,0));}
 private void render(){if(livingScene!=null){livingScene.stop();livingScene=null;}if(embeddedSanctum!=null){embeddedSanctum.pause();embeddedSanctum=null;}if(sanctum!=null){sanctum.setRunning(false);sanctum=null;}body.removeAllViews();nav.removeAllViews();if(!ready){login();return;}headerBar.setVisibility(View.VISIBLE);root.setBackgroundColor(bg);backButton.setVisibility(View.VISIBLE);navScroll.setVisibility(View.GONE);if(page.equals("Home"))page="Lobby";JSONObject wallet=obj(secure,"wallet");status.setText(profile.optString("display_name","Summoner")+"  |  "+wallet.optLong("gp")+" GP  |  "+wallet.optLong("essence")+" Essence");switch(page){case "Lobby":lobby();break;case "Sanctum":home();break;case "Collection":collection();break;case "Review":review();break;case "Progression":progression();break;case "Prompt":prompt();break;case "Codex":codex();break;case "Daily":daily();break;case "Shop":shop();break;case "Achievements":achievements();break;case "Profile":profilePage();break;case "History":historyPage();break;case "Settings":settings();break;case "Detail":detail();break;case "More":more();break;default:lobby();}}
 private LinearLayout[] workspacePanels(){LinearLayout row=new LinearLayout(this);body.addView(row,new LinearLayout.LayoutParams(-1,dp(Math.max(230,getResources().getConfiguration().screenHeightDp-86))));LinearLayout[] panes=new LinearLayout[2];for(int i=0;i<2;i++){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,i==0?.9f:1.1f);lp.setMargins(dp(3),0,dp(3),0);row.addView(scroll,lp);panes[i]=new LinearLayout(this);panes[i].setOrientation(LinearLayout.VERTICAL);panes[i].setPadding(dp(12),dp(12),dp(12),dp(12));panes[i].setBackground(new PixelFrame(this,panel,gold));scroll.addView(panes[i]);}return panes;}
 private LinearLayout gridCell(LinearLayout[] row,int index,int columns){if(index%columns==0){row[0]=new LinearLayout(this);row[0].setWeightSum(columns);body.addView(row[0],new LinearLayout.LayoutParams(-1,-2));}LinearLayout cell=new LinearLayout(this);cell.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.setMargins(dp(3),dp(3),dp(3),dp(3));row[0].addView(cell,lp);return cell;}
 private int gridColumns(){return Math.max(2,Math.min(5,(getResources().getConfiguration().screenWidthDp-40)/170));}
 private void showLoading(){loadingText.setText(startup?"Preparing your chronicles…":"Genesis connecting…");loadingLayer.setBackground(startup?new LobbyBackdrop():new android.graphics.drawable.ColorDrawable(0xee10191e));loadingSpinner.setVisibility(View.VISIBLE);loadingLayer.setVisibility(View.VISIBLE);loadingLayer.bringToFront();}
 private void hideLoading(){startup=false;loadingLayer.setVisibility(View.GONE);loadingSpinner.setVisibility(View.GONE);}
 private void updateWalletHeader(){JSONObject w=obj(economy,"wallet");status.setText(w.optLong("gp")+" GP  |  "+w.optLong("essence")+" Ess  |  "+w.optInt("tickets")+" Tickets  |  "+w.optInt("tokens")+" Tokens");}
 private void lobby(){
  navScroll.setVisibility(View.GONE);headerBar.setVisibility(View.GONE);livingScene=new LobbyBackdrop();root.setBackground(livingScene);livingScene.start(!prefs.getBoolean("reduceMotion",false));
  LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);body.addView(top,new LinearLayout.LayoutParams(-1,-2));
  LinearLayout account=new LinearLayout(this);top.addView(account,new LinearLayout.LayoutParams(0,-2,1));Button profileButton=button(account,"Profile",()->gotoPage("Profile"));profileButton.setLayoutParams(new LinearLayout.LayoutParams(0,dp(44),1));Button settingsButton=button(account,"Settings",()->gotoPage("Settings"));settingsButton.setLayoutParams(new LinearLayout.LayoutParams(0,dp(44),1));
  LinearLayout logo=new LinearLayout(this);logo.setOrientation(LinearLayout.VERTICAL);top.addView(logo,new LinearLayout.LayoutParams(0,-2,1));asset(logo,"media/branding/genesis-logo.png",52);
  JSONObject wallet=obj(economy,"wallet");TextView balances=new TextView(this);PixelFrame.type(balances);balances.setTextSize(11);balances.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);balances.setText(wallet.optLong("gp")+" GP · "+wallet.optLong("essence")+" Ess\n"+wallet.optInt("tickets")+" Tickets · "+wallet.optInt("tokens")+" Tokens");top.addView(balances,new LinearLayout.LayoutParams(0,dp(48),1.1f));
  LinearLayout middle=new LinearLayout(this);body.addView(middle,new LinearLayout.LayoutParams(-1,dp(Math.max(176,getResources().getConfiguration().screenHeightDp-140))));
  ScrollView quickScroll=new ScrollView(this);middle.addView(quickScroll,new LinearLayout.LayoutParams(dp(110),-1));LinearLayout quick=new LinearLayout(this);quick.setOrientation(LinearLayout.VERTICAL);quickScroll.addView(quick);for(String route:new String[]{"Daily","Achievements","Shop","Codex"})button(quick,route,()->gotoPage(route));
  LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setGravity(Gravity.CENTER);middle.addView(hero,new LinearLayout.LayoutParams(0,-1,1));
  JSONObject chosen=lobbyCharacter();if(chosen==null){asset(hero,"media/branding/genesis-mark.png",100);text(hero,"Your chronicle begins here",13,gold);}else{selected=chosen.optString("serverRegistryId");thumbnail(hero,chosen,Math.max(60,Math.min(130,getResources().getConfiguration().screenHeightDp-240)));TextView title=text(hero,name(chosen),15,gold);title.setGravity(Gravity.CENTER);TextView desc=text(hero,chosen.optString("race")+" · "+chosen.optString("class"),12,muted);desc.setGravity(Gravity.CENTER);}button(hero,"Choose lobby character",this::chooseLobbyCharacter);
  LinearLayout entry=new LinearLayout(this);entry.setOrientation(LinearLayout.VERTICAL);entry.setGravity(Gravity.BOTTOM);middle.addView(entry,new LinearLayout.LayoutParams(dp(136),-1));if(pending.length()>0)button(entry,"Pending: "+pending.length(),()->{activeSummons.clear();for(int i=0;i<pending.length();i++)activeSummons.add(pending.optJSONObject(i));gotoPage("Sanctum");});button(entry,"ENTER\nSANCTUM",()->gotoPage("Sanctum"));
  LinearLayout bottom=new LinearLayout(this);body.addView(bottom);for(String route:new String[]{"Collection","Progression","Prompt","History"}){Button b=button(bottom,route,()->gotoPage(route));b.setLayoutParams(new LinearLayout.LayoutParams(dp(112),dp(44)));}
 }
 private JSONObject lobbyCharacter(){String wanted=prefs.getString("lobbyCharacter:"+profile.optString("user_id"),"");JSONObject fallback=null;for(int i=0;i<characters.length();i++){JSONObject c=characters.optJSONObject(i);if(c.optString("serverRegistryId").equals(wanted))return c;if(fallback==null||(!fallback.optBoolean("favorite")&&c.optBoolean("favorite")))fallback=c;}return fallback;}
 private void chooseLobbyCharacter(){if(characters.length()==0){alert("Keep a character first to display it here.");return;}String[] labels=new String[characters.length()];for(int i=0;i<labels.length;i++){JSONObject c=characters.optJSONObject(i);labels[i]=name(c)+" · "+c.optString("race")+" · "+c.optString("characterId");}new AlertDialog.Builder(this).setTitle("Lobby character").setItems(labels,(d,i)->{prefs.edit().putString("lobbyCharacter:"+profile.optString("user_id"),characters.optJSONObject(i).optString("serverRegistryId")).apply();render();}).show();}
 @Override public void onBackPressed(){if(busy)return;if(ready&&!page.equals("Lobby")){gotoPage("Lobby");return;}super.onBackPressed();}
 private void more(){heading("Your chronicles");for(String p:new String[]{"Shop","Codex","Daily","Achievements","Profile","History","Settings"})button(body,p,()->gotoPage(p));}
 private void home(){heading("Summoning Sanctum");LinearLayout saved=body;JSONObject w=obj(economy,"wallet");LinearLayout row=new LinearLayout(this);body.addView(row,new LinearLayout.LayoutParams(-1,dp(Math.max(210,getResources().getConfiguration().screenHeightDp-94))));embeddedSanctum=new SanctumPanel(this,prefs,audio,this::asset,activeSummons,summonChoices,this::inlineDecision);row.addView(embeddedSanctum,new LinearLayout.LayoutParams(0,-1,1.05f));ScrollView scroll=new ScrollView(this);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,1);lp.setMargins(dp(8),0,0,0);row.addView(scroll,lp);LinearLayout controls=new LinearLayout(this);controls.setOrientation(LinearLayout.VERTICAL);controls.setPadding(dp(8),dp(4),dp(8),dp(4));controls.setBackground(new PixelFrame(this,panel,gold));scroll.addView(controls);body=controls;try{button(body,"Summon ×1 · 12 GP",()->summon(1)).setEnabled(w.optLong("gp")>=12);button(body,"Summon ×10 · 120 GP",()->summon(10)).setEnabled(w.optLong("gp")>=120);button(body,"Use 1 summon ticket",()->mutate("genesis_v2_summon",json("p_count",1,"p_use_ticket",true),true)).setEnabled(w.optInt("tickets")>=1);button(body,"Use 10 summon tickets",()->mutate("genesis_v2_summon",json("p_count",10,"p_use_ticket",true),true)).setEnabled(w.optInt("tickets")>=10);note("Earn GP and tickets through Daily missions. Summon results give no GP. No purchases or cash rewards.");note("SR+ guaranteed within "+(40-w.optInt("sr_pity"))+" summons. Mythic guaranteed within "+(90-w.optInt("mythic_pity"))+" summons.");note("Next Mythic chance: "+String.format(Locale.US,"%.1f%%",economy.optDouble("mythic_chance")*100));button(body,"Rarity details",()->alert("Common 3★: 60%\nRare 4★: 30%\nSuper Rare 5★: 7%\nEpic 6★: 2.5%\nMythic 7★: 0.5%\n\nBase odds before pity. Mythic chance rises by 0.5 percentage points per summon from summon 70 (1%) to 89 (10.5%); summon 90 guarantees Mythic. SR+ resets SR pity; only Mythic resets Mythic pity. At SR guarantee, the remaining non-Mythic chance is divided SR:Epic 7:2.5. Race is selected equally from eligible races. Both counters are always active, including tickets."));if(pending.length()>0)button(body,"Review pending ("+pending.length()+")",()->{activeSummons.clear();for(int i=0;i<pending.length();i++)activeSummons.add(pending.optJSONObject(i));render();});}finally{body=saved;}}


 private void summon(int n){mutate("genesis_v2_summon",json("p_count",n,"p_use_ticket",false),true);}
 private void reveal(JSONArray rows){
  ArrayList<JSONObject> results=new ArrayList<>();
  for(int i=0;i<rows.length();i++){JSONObject row=rows.optJSONObject(i);if(row==null)continue;for(int j=0;j<pending.length();j++){JSONObject c=pending.optJSONObject(j);if(c.optString("serverRegistryId").equals(row.optString("registry_id"))){results.add(c);break;}}}
  if(results.isEmpty()){alert("Results are saved. Open Review pending characters to choose Keep or Discard.");return;}
  activeSummons.clear();activeSummons.addAll(results);page="Sanctum";render();
 }

 private void inlineDecision(JSONObject c,boolean keep,java.util.function.Consumer<String> done){
  if(busy){done.accept("Another action is still running. Please retry.");return;}
  busy=true;showLoading();worker.execute(()->{String error=null;try{JSONObject args=json("p_registry_id",c.optString("serverRegistryId"),"p_keep",keep);try{rpc("genesis_character_decide",args);}catch(IOException ex){rpc("genesis_character_decide",args);}refresh();}catch(Exception ex){error="Could not confirm the result. Retry the same choice. "+ex.getMessage();}final String failure=error;runOnUiThread(()->{busy=false;hideLoading();if(isDestroyed())return;if(failure==null){summonChoices.put(c.optString("serverRegistryId"),keep?"Kept":"Discarded");updateWalletHeader();}done.accept(failure);});});
 }
 private void bulkCleanup(){
  ArrayList<JSONObject> candidates=new ArrayList<>();
  for(int i=0;i<characters.length();i++){JSONObject c=characters.optJSONObject(i);if(!c.optBoolean("favorite")&&c.optString("customName").trim().isEmpty())candidates.add(c);}
  if(candidates.isEmpty()){alert("No unnamed, non-favorite characters to clean up.");return;}
  String[] labels=new String[candidates.size()];boolean[] checked=new boolean[candidates.size()];Arrays.fill(checked,true);
  for(int i=0;i<labels.length;i++){JSONObject c=candidates.get(i);labels[i]=obj(c,"rarity").optString("name")+" · "+c.optString("race")+" · CP "+c.optInt("combatPower")+"\n"+c.optString("characterId");}
  new AlertDialog.Builder(this).setTitle("Review "+labels.length+" unnamed characters").setMultiChoiceItems(labels,checked,(d,i,on)->checked[i]=on).setNegativeButton("Cancel",null).setPositiveButton("Review deletion",(d,w)->{
   JSONArray ids=new JSONArray();for(int i=0;i<checked.length;i++)if(checked[i])ids.put(candidates.get(i).optString("serverRegistryId"));
   if(ids.length()==0){alert("No characters selected.");return;}
   new AlertDialog.Builder(this).setTitle("Discard "+ids.length()+" characters?").setMessage("Named and favorite characters are protected. Selected characters will leave Collection permanently. History stays; no refund or pity change.").setNegativeButton("Cancel",null).setPositiveButton("Discard "+ids.length(),(confirm,which)->{
    JSONObject args=json("p_ids",ids,"p_request_key",UUID.randomUUID().toString());
    task(()->{JSONObject result;try{result=rpc("genesis_bulk_discard_unnamed",args);}catch(IOException ex){result=rpc("genesis_bulk_discard_unnamed",args);}refresh();return result;},x->{render();alert(((JSONObject)x).optInt("discarded")+" characters removed from Collection.");});
   }).show();
  }).show();
 }
 private void review(){
  heading("Keep or discard");note("Only characters you keep enter Collection. Unresolved results stay here if you close the app.");
  note("Discard removes the playable character. History and discovery records remain. No refund; pity is unchanged.");
  if(pending.length()==0){note("All results reviewed.");button(body,"Back to Lobby",()->gotoPage("Lobby"));return;}
  note(pending.length()+" pending characters");
  for(int i=0;i<Math.min(pageSize,pending.length());i++){
   JSONObject c=pending.optJSONObject(i);String id=c.optString("serverRegistryId");hero(body,c,false);
   button(body,"Keep · Save to Collection",()->decide(id,true));
   button(body,"Discard",()->new AlertDialog.Builder(this).setTitle("Discard this character?").setMessage(c.optString("race")+" · "+obj(c,"rarity").optString("name")+" · CP "+c.optInt("combatPower")+"\nThis character will not enter Collection. This choice cannot be undone.").setNegativeButton("Cancel",null).setPositiveButton("Discard",(d,w)->decide(id,false)).show());
  }
  if(pageSize<pending.length())button(body,"Load more",()->{pageSize+=30;render();});
 }
 private void decide(String id,boolean keep){
  task(()->{JSONObject args=json("p_registry_id",id,"p_keep",keep);try{rpc("genesis_character_decide",args);}catch(IOException ex){rpc("genesis_character_decide",args);}refresh();return null;},x->{page="Review";render();if(keep)new AlertDialog.Builder(this).setTitle("Saved to Collection").setMessage("You can now name and manage this character.").setNegativeButton("Continue reviewing",null).setPositiveButton("Open character",(d,w)->{selected=id;gotoPage("Detail");}).show();});
 }
 private void hero(LinearLayout parent,JSONObject c,boolean controls){LinearLayout box=card(parent);asset(box,"media/rarities/"+(c.optBoolean("legacy",true)?"":"v2/")+slug(obj(c,"rarity").optString("name"))+".png",prefs.getBoolean("compact",false)?44:52);thumbnail(box,c,prefs.getBoolean("compact",false)?76:105);text(box,(c.optBoolean("legacy",true)?"[Legacy] ":"")+name(c)+(c.optBoolean("favorite")?" ♥":""),20,white);text(box,c.optString("race")+" · "+c.optString("class"),14,muted);text(box,"CP "+c.optInt("combatPower")+" · Lv. "+obj(c,"progression").optInt("level",1),15,gold);if(controls)button(box,"View character",()->{selected=c.optString("serverRegistryId");gotoPage("Detail");});}
 private void collection(){heading("Collection");button(body,"Clean up unnamed characters",this::bulkCleanup);if(pending.length()>0)button(body,"Review pending characters ("+pending.length()+")",()->gotoPage("Review"));note(characters.length()+" characters");EditText q=input(body,"Search name, race, class or ID",InputType.TYPE_CLASS_TEXT);q.setText(search);button(body,"Apply search",()->{search=q.getText().toString().trim().toLowerCase(Locale.ROOT);pageSize=30;render();});button(body,"Filter: "+filter,()->{String[] options={"All","Favorites","Legacy","Common","Uncommon","Rare","Special Rare","Super Rare","Super Special Rare","Epic","Legendary","Mythical","Primordial","Mythic"};new AlertDialog.Builder(this).setItems(options,(d,i)->{filter=options[i];pageSize=30;render();}).show();});LinearLayout[] gridRow={null};int columns=gridColumns();int count=0;for(int i=0;i<characters.length();i++){JSONObject c=characters.optJSONObject(i);boolean matches=filter.equals("All")||(filter.equals("Favorites")?c.optBoolean("favorite"):filter.equals("Legacy")?c.optBoolean("legacy",true):obj(c,"rarity").optString("name").equals(filter));String key=(name(c)+c.optString("race")+c.optString("class")+c.optString("characterId")).toLowerCase(Locale.ROOT);if(matches&&key.contains(search)){if(count<pageSize)hero(gridCell(gridRow,count,columns),c,true);count++;}}if(count==0)note("No matching characters.");if(count>pageSize)button(body,"Load more",()->{pageSize+=30;render();});}
 private void equipmentPortrait(LinearLayout panel,JSONObject c){
  text(panel,name(c),19,gold);text(panel,c.optString("race")+" · "+c.optString("class"),13,muted);thumbnail(panel,c,145);text(panel,"Lv. "+obj(c,"progression").optInt("level",1)+"  |  CP "+c.optInt("combatPower"),14,white);
  String[] slots={"weapon","armor","accessory","relic","artifact"};for(String slot:slots){JSONObject equipment=obj(obj(c,"equipment"),slot);LinearLayout box=card(panel);text(box,slot.toUpperCase(Locale.ROOT)+" +"+(slot.equals("weapon")?c.optInt("weaponUpgrade"):equipment.optInt("upgrade")),12,gold);text(box,slot.equals("weapon")?c.optString("weapon"):equipment.optString("name","Unequipped"),12,white);}
 }
 private void selectCharacter(){String[] labels=new String[characters.length()];for(int i=0;i<labels.length;i++){JSONObject c=characters.optJSONObject(i);labels[i]=name(c)+" · "+c.optString("characterId");}if(labels.length==0){alert("Summon a character first.");return;}new AlertDialog.Builder(this).setTitle("Choose a character").setItems(labels,(d,i)->{selected=characters.optJSONObject(i).optString("serverRegistryId");render();}).show();}
 private void detail(){heading("Character dossier");JSONObject c=current();if(c==null){heading("Choose a character");button(body,"Back to Lobby",()->gotoPage("Lobby"));return;}LinearLayout saved=body;LinearLayout[] panes=workspacePanels();equipmentPortrait(panes[0],c);body=panes[1];try{artwork(c);button(body,c.optBoolean("favorite")?"Remove favorite":"Favorite",()->mutate("genesis_character_set_favorite",json("p_registry_id",selected,"p_favorite",!c.optBoolean("favorite")),false));button(body,"Rename",()->{EditText e=new EditText(this);e.setSingleLine(true);e.setText(c.optString("customName"));e.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(48)});new AlertDialog.Builder(this).setTitle("Character name").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->mutate("genesis_character_set_name",json("p_registry_id",selected,"p_custom_name",e.getText().toString()),false)).show();});for(String k:new String[]{"characterId","seed","raceCategory","gender","age","origin","subclass","faction","affinity","title","ability","ultimate","passive","powerType","magicType","trait","personality","alignment","weapon","weaponCategory","weaponEffect"})note(k.replaceAll("([a-z])([A-Z])","$1 $2")+": "+c.optString(k));text(body,"Character stats",20,gold);try{JSONObject stats=new JSONObject(engine.call("nativeStats",c.toString()));for(String key:new String[]{"STR","AGI","INT","DEF","VIT","LCK"})note(key+": "+stats.optInt(key));}catch(JSONException ignored){}text(body,"Equipment",20,gold);JSONObject eq=obj(c,"equipment");for(String k:new String[]{"armor","accessory","relic","artifact"}){JSONObject e=obj(eq,k);note(k+": "+e.optString("name")+" +"+e.optInt("upgrade")+" · "+obj(e,"rarity").optString("name"));}note(c.optString("lore"));button(body,"Archive character",()->new AlertDialog.Builder(this).setTitle("Archive this character?").setMessage("It will leave your active Collection. This edition has no restore control.").setNegativeButton("Keep",null).setPositiveButton("Archive",(d,w)->{page="Collection";mutate("genesis_character_archive",json("p_registry_id",selected),false);}).show());}finally{body=saved;}}
 private void progression(){heading("Character progression");button(body,"Choose character",this::selectCharacter);JSONObject c=current();if(c==null){note("Choose a Collection character to train or upgrade.");return;}LinearLayout saved=body;LinearLayout[] panes=workspacePanels();equipmentPortrait(panes[0],c);body=panes[1];try{JSONObject p=obj(c,"progression");String[] stages={"Base","Awakened","Ascended","Transcendent"};note(stages[Math.min(3,p.optInt("stage"))]+" · EXP "+p.optInt("xp"));int lv=p.optInt("level",1);note("Next training cost: "+Math.max(12,Math.round(10+lv*2.4))+" Essence");button(body,"Train +1",()->mutate("genesis_character_train",json("p_registry_id",selected,"p_levels",1),true)).setEnabled(lv<100);button(body,"Train ×5",()->mutate("genesis_character_train",json("p_registry_id",selected,"p_levels",5),true)).setEnabled(lv<100);note("Evolution: Awakened Lv25 / 250 Essence; Ascended Lv50 / 600; Transcendent Lv80 / 1200.");button(body,"Advance evolution",()->mutate("genesis_character_ascend",json("p_registry_id",selected),true)).setEnabled(p.optInt("stage")<3);int w=c.optInt("weaponUpgrade");button(body,"Weapon +"+w+" · Upgrade ("+(45+w*35+w*w*4)+" Essence)",()->mutate("genesis_character_upgrade_weapon",json("p_registry_id",selected),true)).setEnabled(w<10);for(String slot:new String[]{"armor","accessory","relic","artifact"}){JSONObject e=obj(obj(c,"equipment"),slot);int level=e.optInt("upgrade"),stars=obj(e,"rarity").optInt("stars",1);long cost=Math.round((30+level*26+level*level*3)*(1+(stars-1)*.08));note(e.optString("name"));button(body,slot+" +"+level+" · Upgrade ("+cost+" Essence)",()->mutate("genesis_character_upgrade_equipment",json("p_registry_id",selected,"p_slot",slot),true)).setEnabled(level<10);}}finally{body=saved;}}
 private void prompt(){heading("Prompt Studio");button(body,"Choose character",this::selectCharacter);JSONObject c=current();if(c==null){note("Choose a character from Collection.");return;}text(body,name(c)+" · "+c.optString("race"),16,gold);final String generatedPrompt=engine.call("nativePrompt",c.toString());LinearLayout actions=new LinearLayout(this);body.addView(actions);Button copy=button(actions,"Copy prompt",()->{android.content.ClipboardManager clipboard=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);clipboard.setPrimaryClip(ClipData.newPlainText("Genesis Splash Art",generatedPrompt));alert("Prompt copied.");});copy.setLayoutParams(new LinearLayout.LayoutParams(0,dp(44),1));Button upload=button(actions,"Upload artwork",()->{uploadId=selected;uploadPrompt=generatedPrompt;Intent pick=new Intent(Intent.ACTION_OPEN_DOCUMENT);pick.setType("image/*");pick.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"image/png","image/jpeg","image/webp"});pick.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(pick,64);});upload.setLayoutParams(new LinearLayout.LayoutParams(0,dp(44),1));TextView output=text(card(body),generatedPrompt,13,white);output.setTextIsSelectable(true);artwork(c);note("End of prompt");}

 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request!=64||result!=RESULT_OK||data==null||data.getData()==null)return;android.net.Uri uri=data.getData();String id=uploadId,prompt=uploadPrompt;if(id.isEmpty())return;task(()->{String mime=getContentResolver().getType(uri);if(!Arrays.asList("image/png","image/jpeg","image/webp").contains(mime))throw new IOException("Use PNG, JPEG or WebP.");byte[] content;try(InputStream in=getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("Unable to open image");content=bytes(in,10485760);}BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(content,0,content.length,bounds);if(bounds.outWidth<=0)throw new IOException("Invalid image file");String path=profile.getString("user_id")+"/"+id+"/primary";api.upload("/storage/v1/object/genesis-character-art/"+path,content,mime);rpc("genesis_character_media_upsert",json("p_registry_id",id,"p_storage_path",path,"p_mime_type",mime,"p_file_size",content.length,"p_prompt_snapshot",prompt));refresh();return null;},x->{render();alert("Artwork saved to this character.");});}
 private void artwork(JSONObject c){String id=c.optString("serverRegistryId"),path="";for(int i=0;i<media.length();i++){JSONObject m=media.optJSONObject(i);if(m.optString("registry_id").equals(id)){path=m.optString("storage_path");break;}}if(path.isEmpty()){note("Artwork not submitted. Race emblem is shown.");return;}final String storagePath=path;button(body,"View submitted artwork",()->task(()->{JSONObject signed=api.storage("/storage/v1/object/sign/genesis-character-art/"+storagePath,json("expiresIn",300));String part=signed.optString("signedURL",signed.optString("signedUrl"));if(!part.startsWith("/object/"))throw new IOException("Unexpected artwork response");java.net.HttpURLConnection conn=(java.net.HttpURLConnection)new java.net.URL(BuildConfig.SUPABASE_URL.replaceAll("/+$","")+"/storage/v1"+part).openConnection();conn.setInstanceFollowRedirects(false);conn.setConnectTimeout(15000);conn.setReadTimeout(20000);try(InputStream in=conn.getInputStream()){byte[] bytes=bytes(in,10485760);BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);o.inSampleSize=1;while(o.outWidth/o.inSampleSize>1600||o.outHeight/o.inSampleSize>1600)o.inSampleSize*=2;o.inJustDecodeBounds=false;return BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);}finally{conn.disconnect();}},x->{ImageView v=new ImageView(this);v.setAdjustViewBounds(true);v.setImageBitmap((Bitmap)x);new AlertDialog.Builder(this).setTitle(name(c)).setView(v).setPositiveButton("Close",null).show();status.setText("Artwork loaded");}));}

 private void thumbnail(LinearLayout box,JSONObject character,int height){
  JSONObject found=null;for(int i=0;i<media.length();i++){JSONObject m=media.optJSONObject(i);if(m.optString("registry_id").equals(character.optString("serverRegistryId"))){found=m;break;}}
  if(found==null){asset(box,"media/races/"+slug(character.optString("baseRace","unknown"))+".png",height);return;}
  final JSONObject item=found;final String key=item.optString("storage_path")+item.optString("updated_at");
  ImageView view=new ImageView(this);view.setScaleType(ImageView.ScaleType.FIT_CENTER);view.setContentDescription(name(character)+" artwork");box.addView(view,new LinearLayout.LayoutParams(-1,dp(height)));Bitmap cached=cache.get(key);if(cached!=null){view.setImageBitmap(cached);return;}
  images.execute(()->{try{Bitmap bitmap=downloadArtwork(item.getString("storage_path"),800);if(bitmap!=null){cache.put(key,bitmap);runOnUiThread(()->{if(!isDestroyed())view.setImageBitmap(bitmap);});}}catch(Exception ex){runOnUiThread(()->{if(!isDestroyed())view.setContentDescription("Artwork unavailable. Refresh to retry.");});}});
 }
 private Bitmap downloadArtwork(String path,int maxSide)throws Exception {
  JSONObject signed=api.storage("/storage/v1/object/sign/genesis-character-art/"+path,json("expiresIn",300));String suffix=signed.optString("signedURL",signed.optString("signedUrl"));if(!suffix.startsWith("/object/"))throw new IOException("Unexpected artwork response");
  java.net.HttpURLConnection connection=(java.net.HttpURLConnection)new java.net.URL(BuildConfig.SUPABASE_URL.replaceAll("/+$","")+"/storage/v1"+suffix).openConnection();connection.setInstanceFollowRedirects(false);connection.setConnectTimeout(15000);connection.setReadTimeout(20000);
  try(InputStream in=connection.getInputStream()){byte[] data=bytes(in,10485760);BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(data,0,data.length,o);o.inSampleSize=1;while(o.outWidth/o.inSampleSize>maxSide||o.outHeight/o.inSampleSize>maxSide)o.inSampleSize*=2;o.inJustDecodeBounds=false;return BitmapFactory.decodeByteArray(data,0,data.length,o);}finally{connection.disconnect();}
 }

 private void codex(){heading("Codex");JSONArray entries=arr(meta,"codex");note(entries.length()+" discoveries verified by the server");Set<String> discovered=new HashSet<>();for(int i=0;i<entries.length();i++){JSONObject e=entries.optJSONObject(i);discovered.add(e.optString("codex_type")+"|"+e.optString("entry_key"));}button(body,"All discoveries",()->{StringBuilder b=new StringBuilder();for(int i=0;i<entries.length();i++){JSONObject e=entries.optJSONObject(i);b.append(e.optString("codex_type")).append(" · ").append(e.optString("entry_key")).append(" ×").append(e.optInt("times_obtained")).append('\n');}alert(b.length()==0?"No discoveries yet.":b.toString());});LinearLayout[] gridRow={null};int columns=gridColumns();JSONArray races=arr(obj(catalog,"data"),"races");for(int i=0;i<races.length();i++){String race=races.optJSONArray(i).optString(0);boolean known=discovered.contains("race|"+race);LinearLayout box=card(gridCell(gridRow,i,columns));asset(box,"media/races/"+(known?slug(race):"unknown")+".png",85);text(box,race+" · "+obj(catalog,"families").optString(race),17,gold);text(box,known?"Discovered":"Not discovered",13,muted);}}
 private void achievements(){heading("Achievements");Set<String> unlocked=new HashSet<>();JSONArray earned=arr(meta,"achievements");for(int i=0;i<earned.length();i++)unlocked.add(earned.optJSONObject(i).optString("achievement_id"));note(unlocked.size()+" unlocked · "+obj(meta,"profile").optInt("achievement_points")+" AP. Legacy achievements retain earned rewards; retired targets are marked below.");LinearLayout[] gridRow={null};int columns=gridColumns();JSONArray defs=arr(catalog,"achievements");for(int i=0;i<defs.length();i++){JSONObject a=defs.optJSONObject(i);LinearLayout box=card(gridCell(gridRow,i,columns));text(box,a.optString("name")+(unlocked.contains(a.optString("id"))?" ✓":""),18,gold);text(box,a.optString("desc"),14,muted);text(box,a.optInt("ap")+" AP · "+reward(obj(a,"reward")),13,white);JSONArray progress=obj(meta,"achievement_progress").optJSONArray(a.optString("id"));if(a.optBoolean("legacy")&&!unlocked.contains(a.optString("id")))text(box,"Retired target · historical progress retained",13,muted);if(progress!=null)text(box,progress.optLong(0)+" / "+progress.optLong(1),13,muted);}}
 private String reward(JSONObject r){List<String> a=new ArrayList<>();for(String k:new String[]{"gp","essence","xp"})if(r.optLong(k)>0)a.add(r.optLong(k)+" "+k.toUpperCase(Locale.ROOT));return android.text.TextUtils.join(" + ",a);}
 private void daily(){heading("Daily rewards");note("Server date: "+economy.optString("server_date")+" · Resets at 00:00 UTC. GP and tickets do not expire. No streak penalty.");String[] ids={"checkin","summon1","summon3","train1","upgrade1"};String[] titles={"Daily check-in","Summon 1 character","Summon 3 characters","Train once","Upgrade once"};String[] rewards={"60 GP + 50 Essence + 10 Tokens + 1 Ticket","12 GP","24 GP","12 GP + 15 Essence","12 GP + 20 Essence"};LinearLayout[] gridRow={null};int columns=gridColumns();JSONArray claims=arr(economy,"claims");for(int i=0;i<ids.length;i++){final String id=ids[i];int target=i==2?3:1;boolean claimed=false;for(int j=0;j<claims.length();j++)if(id.equals(claims.optString(j)))claimed=true;LinearLayout box=card(gridCell(gridRow,i,columns));text(box,titles[i],18,gold);text(box,rewards[i],14,muted);int progress=obj(economy,"progress").optInt(id);text(box,Math.min(progress,target)+" / "+target,13,white);button(box,claimed?"Claimed":"Claim reward",()->mutate("genesis_v2_claim",json("p_mission",id),true)).setEnabled(!claimed&&progress>=target);}}
 private void shop(){heading("Exchange Shop");int tokens=obj(economy,"wallet").optInt("tokens");note(tokens+" Genesis Tokens · Earned through Daily rewards");note("Fixed items and prices. No random boxes or chance boosts.");String[] ids={"essence50","essence150"};int[] costs={5,12},amounts={50,150};for(int i=0;i<ids.length;i++){final String id=ids[i];final int cost=costs[i],amount=amounts[i];button(body,amount+" Essence · "+cost+" Tokens",()->new AlertDialog.Builder(this).setTitle("Confirm exchange").setMessage("Exchange "+cost+" Tokens for "+amount+" Essence?").setNegativeButton("Cancel",null).setPositiveButton("Exchange",(d,w)->mutate("genesis_v2_shop_buy",json("p_item",id),true)).show()).setEnabled(tokens>=cost);}}
 private void profilePage(){heading("Summoner profile");LinearLayout saved=body;LinearLayout[] panes=workspacePanels();body=panes[0];try{note(profile.optString("player_id"));EditText name=input(body,"Display name",InputType.TYPE_CLASS_TEXT);name.setText(profile.optString("display_name"));name.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(28)});button(body,"Save display name",()->mutate("genesis_profile_ensure",json("p_display_name",name.getText().toString()),false));body=panes[1];JSONObject p=obj(meta,"profile");note("Level "+p.optInt("summoner_level",1)+" · Lifetime EXP "+p.optLong("summoner_xp"));note(p.optInt("achievement_points")+" AP · "+p.optString("achievement_rank"));JSONObject stats=obj(meta,"stats");for(String k:new String[]{"total_summons","ten_pulls","highest_combat_power","highest_weapon_power","daily_mission_claims","perfect_daily_days","full_login_cycles"})note(k.replace('_',' ')+": "+stats.optLong(k));button(body,"Sign out",this::logout);}finally{body=saved;}}
 private void historyPage(){heading("History & economy ledger");note("Latest 200 characters and 10 economy events");JSONArray ledger=arr(secure,"ledger");for(int i=0;i<ledger.length();i++){JSONObject e=ledger.optJSONObject(i);text(card(body),e.optString("event_type")+"\nGP "+e.optLong("gp_delta")+" · Essence "+e.optLong("essence_delta")+"\n"+e.optString("created_at"),14,muted);}for(int i=0;i<Math.min(pageSize,history.length());i++){JSONObject h=history.optJSONObject(i);LinearLayout box=card(body);asset(box,"media/rarities/"+(h.optString("seed").startsWith("G165-")?"v2/":"")+slug(h.optString("rarity_name"))+".png",70);text(box,h.optString("character_id")+"\n"+h.optString("created_at")+(h.optBoolean("archived")?"\nArchived":""),14,white);}if(pageSize<history.length())button(body,"Load more",()->{pageSize+=30;render();});}
 private void volume(String label,String key,int defaultValue){
  TextView value=text(body,label+": "+prefs.getInt(key,defaultValue)+"%",14,muted);
  SeekBar bar=new SeekBar(this);bar.setMax(100);bar.setProgress(prefs.getInt(key,defaultValue));bar.setContentDescription(label);body.addView(bar,new LinearLayout.LayoutParams(-1,dp(48)));
  bar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int progress,boolean fromUser){value.setText(label+": "+progress+"%");if(fromUser){prefs.edit().putInt(key,progress).apply();audio.settingsChanged();}}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});
 }
 private void settings(){heading("Settings");button(body,"Preview new rarity badges",()->{ScrollView scroll=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);scroll.addView(list);for(int i=0;i<5;i++)list.addView(new RarityBadgeView(this,i),new LinearLayout.LayoutParams(dp(290),dp(64)));new AlertDialog.Builder(this).setTitle("Rarity badges").setView(scroll).setPositiveButton("Close",null).show();});button(body,"Check bundled images",this::checkBundledImages);toggle("Background music","music",true);volume("Music volume","musicVolume",35);toggle("Sound effects","sound",true);volume("Effects volume","sfxVolume",65);button(body,"Preview rarity effects",()->new AlertDialog.Builder(this).setTitle("Choose rarity effect").setItems(new String[]{"Common","Rare","Super Rare","Epic","Mythic"},(d,i)->presentation.preview(new int[]{0,2,4,6,8}[i])).show());toggle("Reduce motion","reduceMotion",false);toggle("Compact collection","compact",false);button(body,"Refresh account",()->task(()->{refresh();return null;},x->render()));button(body,"Sign out",this::logout);note("Genesis 18.2 · Living UI\nProgress and artwork are stored in your online account. This app stores only encrypted session tokens and display preferences locally.");}
}
